### ISSUE TITLE
Search causes ratelimits

### ISSUE THREAD

**Issue by rrgeorge** [feditext/feditext#119] opened 2023-07-27 22:27 UTC
**Describe the bug**
It seems that using search can trigger rate limit son mastodon. My guess is because it hits the api with every key press

**To Reproduce**
1. To explore tab
2. Type out something to search for
3. Browse search results
4. Start receiving “too many requests” errors 

**Expected behavior**
Not to be rate limited

**Screenshots**
N/a

**(please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 16.5.1
 - App Version 1.7.2(64)

**Additional context**

**Comment by VyrCossont** [comment] 2023-07-27 23:42
The good news is that your guess is wrong: as of a1b73573122f9d2ed68ed70d5be26b8186aedc46, which was back in the Metatext era, there's an 800ms debounce on Explore tab searches (formerly 200ms). I've confirmed using Proxyman that it still works on modern Feditext. The bad news is that I don't know what else might be causing it. We should only be making three calls per chunk when browsing search results: one for the actual results, another two to look up relationships and familiar followers for people searches.

**Comment by rrgeorge** [comment] 2023-07-27 23:59
Oh I think its media_proxy… Since search yields posts from outside my retention, it hits media_proxy a whole bunch

**Comment by VyrCossont** [comment] 2023-08-08 01:02
Accidentally found the root cause, or at least a possible root cause of rate limit exhaustion related to searches: Feditext can't cope with hitting the end of search results, and has no mechanism to stop requesting more once you've scrolled to the bottom. I think this behavior was also present in Metatext. Investigating.

**Comment by VyrCossont** [comment] 2023-10-03 00:13
Definitely also present in Metatext.

**Comment by VyrCossont** [comment] 2024-02-06 22:42
I am investigating this again and baffled as to why other types of timeline *don't* have this problem. https://github.com/feditext/feditext/blob/5c0ec187ac14d165d5e2855ba4c26c857979537e/View%20Controllers/TableViewController.swift#L143 is the view controller responsible for displaying almost any list of things in Metatext and Feditext, and it doesn't have an explicit stop! Whenever the last entry in the table would be displayed, [`UITableView.(_:willDisplay:forRowAt:)`](https://developer.apple.com/documentation/uikit/uitableviewdelegate/1614883-tableview) kicks off a request for the next page of results.

Scrolling to the end of search results calls our  `willDisplay` repeatedly as long as the end is on screen, but scrolling to the end (chronologically, the beginning) of an account timeline doesn't do this, and it gets called only once.

**Comment by VyrCossont** [comment] 2024-02-09 23:20
I think I've fixed this by switching to ID-based paging and fixing the way we track the next page ID. Need to make sure things reset properly when the search query or type is changed.

**Comment by VyrCossont** [comment] 2024-02-12 05:19
Fixed with 1.7.2 build 89.

**Closed as completed** 2024-02-12 05:19 UTC
Labels: bug
