### ISSUE TITLE
invalidStatusCode On bookmark toggle

### ISSUE THREAD

**Issue by hpux735** [feditext/feditext#155] opened 2023-08-02 15:09 UTC
**Describe the bug**
I’ve gotten an invalid status code when trying to “un-bookmark” a post 

**To Reproduce**
1. Go to bookmarks
2. Click on `…`
3. Select “bookmark”

**Expected behavior**
The post should bookmark status should be cleared. 

**(please complete the following information):**
 - Device: iPhone SE gen something
 - OS: 16.5.1
 - App Version 1.7.2 (69)

**Additional context**
JSON:
```
{
  "alertLocation" : {
    "file" : "ViewModels/CollectionItemsViewModel.swift",
    "function" : "events",
    "line" : 356
  },
  "app" : {
    "build" : "69",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "error" : {
    "method" : "POST",
    "reason" : "invalidStatusCode",
    "requestLocation" : {
      "file" : "ServiceLayer/StatusService.swift",
      "function" : "toggleBookmarked()",
      "line" : 66
    },
    "statusCode" : 401,
    "url" : "https://xxx.xxx/api/v1/statuses/964475185536164/bookmark"
  },
  "message" : "POST https://xxx.xxx/api/v1/statuses/964475185536164/bookmark\n\nHTTP Error: 401",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "16.5.1"
  },
  "title" : "HTTPError",
  "type" : "HTTPError"
}
```

**Comment by VyrCossont** [comment] 2023-08-02 17:38
@hpux735 What kind of instance are you using?

**Comment by hpux735** [comment] 2023-08-02 17:55
Oops! Sorry. It’s `14.0.0-dev19-hk25`

**Comment by VyrCossont** [comment] 2023-08-02 18:10
Calckey-based Hajkey, got it.

**Comment by VyrCossont** [comment] 2023-08-03 20:36
Repro confirmed on Hajkey. What happens is that Hajkey doesn't send an updated `bookmarked` value with the post, so Feditext has no idea it's been bookmarked. Selecting the bookmark action again throws an error because it's already been bookmarked.

**Comment by hpux735** [comment] 2023-08-03 20:39
That's very naughty.  Would you like me to open more issues in the hajkey repo?  I feel like a non-insignificant number of these issues really originate there.

**Comment by VyrCossont** [comment] 2023-08-03 20:41
Yes, please. Let me check it with some other Calckey forks and see how widely spread the issue is.

**Comment by VyrCossont** [comment] 2023-08-03 20:44
No repro on Firefish.

**Comment by VyrCossont** [comment] 2023-08-03 20:49
Or Iceshrimp. Bookmark state works fine there. This is just Hajkey, so please open a bug with them, and I'll close this one.

**Closed as completed by VyrCossont** 2023-08-03 20:49 UTC
Labels: Misskey fork, server bug

**Comment by hpux735** [comment] 2023-08-03 20:55
[Hajkey issue](https://codeberg.org/supakaity/hajkey/issues/17)
