### ISSUE TITLE
"Load More" failure on Firefish

### ISSUE THREAD

**Issue by ghost** [feditext/feditext#190] opened 2023-08-11 00:34 UTC
```
{
  "alertLocation" : {
    "file" : "ViewModels/CollectionItemsViewModel.swift",
    "function" : "events",
    "line" : 356
  },
  "app" : {
    "build" : "70",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "message" : "SQLite error 19: FOREIGN KEY constraint failed - while executing `INSERT INTO \"statusRecord\" (\"id\", \"uri\", \"createdAt\", \"editedAt\", \"accountId\", \"content\", \"visibility\", \"sensitive\", \"spoilerText\", \"mediaAttachments\", \"mentions\", \"tags\", \"emojis\", \"reblogsCount\", \"favouritesCount\", \"repliesCount\", \"application\", \"url\", \"inReplyToId\", \"inReplyToAccountId\", \"reblogId\", \"poll\", \"card\", \"language\", \"text\", \"favourited\", \"reblogged\", \"muted\", \"bookmarked\", \"pinned\", \"reactions\") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "16.6"
  },
  "title" : "DatabaseError",
  "type" : "DatabaseError"
}
```

**To Reproduce:**

1. Open the app (Complete restart of the app, not from the multitasking menu)
2. Press the "Load More" dialogue in the feed
3. ![Description of the error (JSON above)](https://github.com/feditext/feditext/assets/121812160/876b0c91-6270-435f-a8e8-c46e5b837367)

I'm just not sure why this happens?

**Comment by VyrCossont** [comment] 2023-08-11 01:16
Thanks for the report! This is a dupe of #124. I've updated 124's title to make it more obvious.

**Closed as completed** 2023-08-11 01:17 UTC
Labels: duplicate, Misskey fork

**Comment by ghost** [comment] 2023-08-11 13:00
ah alright! i'm glad it's already been noticed.
