### ISSUE TITLE
Add an option for showing un-cropped media directly in posts

### ISSUE THREAD

**Issue by yithian** [feditext/feditext#209] opened 2023-08-15 12:02 UTC
**Is your feature request related to a problem? Please describe.**
It's  irritating that posts with an image attached crop the image and that to see the whole thing, you have to tap the image to open it

**Describe the solution you'd like**
I'd like to have the full image displayed directly in the post (in the timeline or trending posts or wherever)

**Describe alternatives you've considered**
An option to display images cropped or un-cropped could be a compromise if defaulting to cropped images is desired

**Comment by VyrCossont** [comment] 2023-08-15 16:01
Duplicate of #134.

**Closed as completed** 2023-08-15 16:01 UTC
