### ISSUE TITLE
App is very sluggish on iOS 17

### ISSUE THREAD

**Issue by evilcookies98** [feditext/feditext#253] opened 2023-09-17 01:35 UTC
The app in general seems very sluggish, and somewhat unresponsive. This happens no matter what I’m doing or what I click instead of merely scrolling along or letting me click things. There is a very noticeable delay when moving from Element to Element or clicking a button. I’m using an iPhone 13 with the release candidate of iOS 17 on it.

**Comment by VyrCossont** [comment] 2023-09-18 21:44
Experiencing this on my own device with the released version of iOS 17.

**Comment by ghecho** [comment] 2023-09-18 23:13
Me too. It happened as soon as I updated to iOS 17.

**Comment by OniriCorpe** [comment] 2023-09-20 15:06
Same on iPadOS 17!

**Comment by VyrCossont** [comment] 2023-09-20 18:46
Looks like [the HTML parsing method we're using](https://developer.apple.com/documentation/foundation/nsattributedstring/1524613-init#discussion) is much, much slower on iOS 17. I've prototyped a few alternatives that replace this pseudo-synchronous invocation of WebKit (from stack samples, it seems to be interleaving a WebKit run loop with the normal one) with [an explicitly async method](https://developer.apple.com/documentation/foundation/nsattributedstring/3335218-loadfromhtml), but none of them are particularly clean, and I've already found and filed one WebKit bug that is triggered by using that method with typical Mastodon posts.

So the next best option is to throw WebKit in the trash and process the AST we're already building with SwiftSoup's sanitizer into an `NSAttributedString` ourselves. This is going to take at least a day or two and will probably have a lot of weird edge cases around nested lists, quotes, etc. but should be a lot faster on *all* supported iOS versions and get us back to usable on iOS 17.

**Comment by VyrCossont** [comment] 2023-09-23 00:58
New AST formatter is about half working. As soon as it's able to handle *most* real-world Mastodon posts, I'll release a new build that uses it.

**Comment by OniriCorpe** [comment] 2023-09-23 02:25
Take the time it needs!

**Comment by evilcookies98** [comment] 2023-09-23 02:31
No rush. The only thing I was in a rush to do is let you guys know this was a problem.Sent from my iPhoneOn Sep 22, 2023, at 10:25 PM, OniriCorpe ***@***.***> wrote:﻿
Take the time it needs!

**Comment by NyaomiDEV** [comment] 2023-09-28 19:05
Hello everyone, I don't know if it should be treated as a separate thing but I noticed that posts under CW are slow to interact with. Specifically, the reveal button isn't really snappy, and it takes up to one second to reveal the CW'd content. I don't know if you can reproduce on your instances, but I was thinking of reporting anyway.

iPhone 11 on iOS 17.0.1. Treehouse instance

**Comment by VyrCossont** [comment] 2023-10-16 19:42
@NyaomiDEV I think that's a separate issue. If you're still experiencing it on the current build, please open a new bug.

Closing this since the API capabilities cache fixed the worst iOS 17 slowdown.

I'm back to working on the new HTML handling after a break, and we might be able to get further speedups there on all supported iOS versions.

**Closed as completed by VyrCossont** 2023-10-16 19:42 UTC
Labels: bug, performance
