### ISSUE TITLE
Eightpoint.app: Instance not supported

### ISSUE THREAD

**Issue by highenergymagic** [feditext/feditext#369] opened 2024-02-11 04:03 UTC
**Describe the bug**
We are the admin of Eightpoint.app. On trying to log into our own instance with this app, we get a message that "In order to provide a safe experience to all users and comply with the App Store Review Guidelines , this instance is not supported."
We were never consulted nor made aware that our instance was tagged in this way, and would object to it being tagged as such.

**To Reproduce**
1. Install and open Feditext.
2. Attempt to login with the 'eightpoint.app' mastodon instance
3. The error previously mentioned shows up
**Expected behavior**
Feditext would connect to and operate with Eightpoint.app normally.

**Screenshots**
Unable to add screenshots. Instance owner is blind

**(please complete the following information):**
 - Device: iPhone 14 pro max
 - OS: iOS 17.3
 - App Version v1.7.2-testflight-59

**Additional context**
We were not made aware that our instance was blocked, and would like to know why this was done so with no consultation with us, and, if possible, get the block removed.

**Comment by ghost** [comment] 2024-02-11 15:49
![Relevant Screenshot](https://github.com/feditext/feditext/assets/159711792/8f9797df-8afe-4418-8942-26c85fe42738)

Hi! I’m Emma,the end user that initially reported this to the instance admin. Since the admin is blind I wanted to upload a screenshot in order to help finish the issue template up

**Comment by VyrCossont** [comment] 2024-02-11 17:29
Dupe of #362. This instance is in one or more of the blocklists we source. Please do not open any more issues related to this instance.

**Closed as not planned by VyrCossont** 2024-02-11 17:29 UTC
Labels: duplicate, wontfix

**Comment by Rosiemma** [comment] 2024-02-11 22:53
So you’re just not gonna explain why you chose to block this beyond we blindly follow abusive fediblock block lists? I already know why this instance was blocked in the past with the user in question is no longer on that instance they left when y’all started your shit. Methinks I’ll be making a stink about this

relevant toots: https://rosiemma.online/notes/9plclfhveg29ssfa
https://rosiemma.online/notes/9pld0eksusyckdzp

**Comment by Rosiemma** [comment] 2024-02-12 11:33
Waiiit now I know why I know your name,you took part in harrassing 8point when tech.lgbt was defederating with them despite LB having already left. Should have known from that start that trusting a LGBT with actually making open source software without injecting their personal beliefs into it was a mistake. And I’m transfem myself,so don’t play the TERF card. so called “inclusive” anything likes to bully anyone who doesn’t fit  perfectly. No better than mastodon.art or tech.lgbt honestly. For the crime of,as someone put it during the tech.lgbt incident, of trying to prevent the “hot allostatic load”. Go read that article and humble yourself,you’re not hot shit,you’re an abusive transfem who hides behind an avatar online. No better than the twitter transfems that falsely accused me of shit.
