### ISSUE TITLE
AnnotatedDecodingError in Suggested Accounts to Follow

### ISSUE THREAD

**Issue by stoklund** [feditext/feditext#384] opened 2024-03-16 17:30 UTC
**Describe the bug**
The ‘Suggested Accounts to Follow’ screen immediately pops up an error dialog.

**To Reproduce**
1. Select ‘Explore’ tab
2. Click on ‘Suggested Accounts to Follow’
3. See error dialog

**Expected behavior**
No error

**Screenshots**
![IMG_0091](https://github.com/feditext/feditext/assets/12660495/8c45a76e-adec-4518-8697-95245e3e23bd)

**(please complete the following information):**
 - Device: iPad mini
 - OS: 17.3.1
 - App Version 1.7.2 (93)

**Additional context**
```
{
  "alertLocation" : {
    "file" : "ViewModels/CollectionItemsViewModel.swift",
    "function" : "request(maxId:minId:)",
    "line" : 370
  },
  "app" : {
    "build" : "93",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "error" : {
    "error" : {
      "typeMismatch" : {
        "context" : {
          "codingPath" : [
            "_JSONKey(stringValue: \"Index 0\", intValue: 0)",
            "CodingKeys(stringValue: \"source\", intValue: nil)"
          ],
          "debugDescription" : "Expected to decode String but found an array instead."
        },
        "type" : "Swift.String"
      }
    },
    "method" : "GET",
    "requestLocation" : {
      "file" : "ServiceLayer/SuggestedAccountListService.swift",
      "function" : "request(maxId:minId:)",
      "line" : 47
    },
    "url" : "https://oldbytes.space/api/v2/suggestions"
  },
  "message" : "GET https://oldbytes.space/api/v2/suggestions\n\ntypeMismatch(type: \"Swift.String\", context: HTTP.AnnotatedDecodingError.EncodableContext(codingPath: [\"_JSONKey(stringValue: \\\"Index 0\\\", intValue: 0)\", \"CodingKeys(stringValue: \\\"source\\\", intValue: nil)\"], debugDescription: \"Expected to decode String but found an array instead.\", underlyingError: nil))",
  "system" : {
    "idiom" : "pad",
    "model" : "iPad",
    "name" : "iPadOS",
    "version" : "17.3.1"
  },
  "title" : "AnnotatedDecodingError",
  "type" : "AnnotatedDecodingError"
}
```

**Comment by VyrCossont** [comment] 2024-03-17 23:12
This is a duplicate of #354, which was a server bug fixed upstream in mastodon/mastodon#29108. Please let the oldbytes.space admin know that they can fix this by upgrading to a Mastodon version with that patch.

**Closed as not planned by VyrCossont** 2024-03-17 23:12 UTC
Labels: duplicate, server bug
