### ISSUE TITLE
Error when attempting Firefish login

### ISSUE THREAD

**Issue by huckabarry** [feditext/feditext#191] opened 2023-08-11 03:21 UTC
Refuses to login to Firefish. Error:500

![image](https://github.com/feditext/feditext/assets/98623388/fd0e79ce-e1d9-420f-b710-65dcb7ea6052)

JSON:

```json
{
  "alertLocation" : {
    "file" : "ViewModels/AddIdentityViewModel.swift",
    "function" : "addIdentity(kind:)",
    "line" : 110
  },
  "app" : {
    "build" : "70",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "error" : {
    "method" : "GET",
    "reason" : "invalidStatusCode",
    "requestLocation" : {
      "file" : "MastodonAPI/NodeInfoClient.swift",
      "function" : "nodeInfo()",
      "line" : 21
    },
    "statusCode" : 500,
    "url" : "https://firefish.social/nodeinfo/2.1"
  },
  "message" : "GET https://firefish.social/nodeinfo/2.1\n\nHTTP Error: 500",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "17.0"
  },
  "title" : "HTTPError",
  "type" : "HTTPError"
}
```

**Comment by VyrCossont** [comment] 2023-08-11 14:36
Congrats, you found a weird one! This looks to be a problem with firefish.social specifically, not Firefish and not Feditext. I'll let the operators know.

**Comment by VyrCossont** [comment] 2023-08-11 14:44
Here are the details: Feditext detects the server type and true server version (not whatever Mastodon version it pretends to be) by reading the server's [NodeInfo](https://github.com/jhass/nodeinfo) doc.

For firefish.social, the [JRD](https://www.packetizer.com/json/jrd/) for NodeInfo lives at https://firefish.social/.well-known/nodeinfo and has these contents:

```json
{
  "links": [
    {
      "rel": "http://nodeinfo.diaspora.software/ns/schema/2.1",
      "href": "https://firefish.social/nodeinfo/2.1"
    },
    {
      "rel": "http://nodeinfo.diaspora.software/ns/schema/2.0",
      "href": "https://firefish.social/nodeinfo/2.0"
    }
  ]
}
```

Unfortunately, at the time of this writing, https://firefish.social/nodeinfo/2.0 and https://firefish.social/nodeinfo/2.1 both take forever to load and then return only:

```
Internal Server Error
```

Now, you might say, hey Vyr, why doesn't Feditext fall back to the normal Mastodon instance info API? Fair point, maybe I'll add that as a recovery method in the future, but in this case, it doesn't work either: https://firefish.social/api/v1/instance has the same problem.

(https://firefish.social/api/v2/instance doesn't exist; Firefish doesn't implement the Mastodon v2 instance API.)

**Comment by VyrCossont** [comment] 2023-08-11 14:50
Following up with `@admin@firefish.social` here: https://universeodon.com/@vyr/110871536261132795

**Comment by ortizdr** [comment] 2023-08-12 02:56
This is happening with my person firefish server as well.

```json
{
  "alertLocation" : {
    "file" : "ViewModels/AddIdentityViewModel.swift",
    "function" : "addIdentity(kind:)",
    "line" : 110
  },
  "app" : {
    "build" : "70",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "error" : {
    "method" : "GET",
    "reason" : "invalidStatusCode",
    "requestLocation" : {
      "file" : "ServiceLayer/APICapabilities+Extensions.swift",
      "function" : "refresh(session:instanceURL:secrets:)",
      "line" : 32
    },
    "statusCode" : 500,
    "url" : "https://firefish.techguy.social/api/v1/instance"
  },
  "message" : "GET https://firefish.techguy.social/api/v1/instance/n/nHTTP Error: 500",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "16.6"
  },
  "title" : "HTTPError",
  "type" : "HTTPError"
}
```

**Comment by VyrCossont** [comment] 2023-08-12 03:01
@ortizdr what version of Firefish are you running? That's not quite the same error, but it's also early in login and also shouldn't be happening. I wonder if there's been a regression in recent Firefish?

**Comment by ortizdr** [comment] 2023-08-12 03:02
@VyrCossont 1.0.4-beta

**Comment by VyrCossont** [comment] 2023-08-12 03:09
My usual test server infosec.town is running 1.0.4 (apparently not beta?) and does not have this issue.

firefish.social is running 1.0.5-dev7 and does.

**Comment by ortizdr** [comment] 2023-08-12 03:22
@VyrCossont I just pulled the latest docker image for firefish and it is still the same version.
So who knows.

**Comment by VyrCossont** [comment] 2023-08-12 18:11
Confirmed firefish.community is also *not* affected by the slow NodeInfo 500 issue. They're running 1.0.5-dev6.

@ortizdr I think the problem is with your install. I recommend asking Firefish support chat on Matrix. Could be that there's something wrong with the Docker setup specifically.

**Comment by VyrCossont** [comment] 2023-08-12 18:17
This doesn't look like a systemic issue with either Firefish or Feditext so I'm going to close this out. @huckabarry if firefish.social doesn't respond in a day or two, give them a prod.

**Closed as completed by VyrCossont** 2023-08-12 18:17 UTC
Labels: Misskey fork, server bug
