### ISSUE TITLE
Crash upon login to Sharkey

### ISSUE THREAD

**Issue by NyaomiDEV** [feditext/feditext#323] opened 2023-12-11 10:30 UTC
**Describe the bug**
FediText crashes upon login to a Sharkey instance (woem.men tested, probably others too)

**To Reproduce**
1. Complete login to a Sharkey instance
2. Observe the app crash

**Expected behavior**
The app should error out, but not outright crash.. at the very least.

**Screenshots**
... :(

**(please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 17.1.2
 - App Version 1.7.2 (80)

**Additional context**
I tried to send a crash report through TestFlight too.

**Comment by puzzler995** [comment] 2023-12-11 23:36
I see the same behavior (although with the same instance, woem.men).
Device: iPhone 14 Pro Max
OS: 17.1.2
Version: 1.7.2 (80)

As a note, it happens once you confirm the login, and then from there renders the app unusable until you delete it and reinstall, even if you have other accounts logged in. I also confirmed this is the behavior on a fresh install.

**Comment by VyrCossont** [comment] 2024-01-24 17:54
I haven't tested against Sharkey yet, but "crashes on login" should be easy to repro. Thanks for the report.

**Comment by technicat** [comment] 2024-01-30 03:36
I tried the current code with sharkey on shonk.social, didn't immediately crash, was able to browse, favorite a status (didn't update the appearance but I got a notification that it got favorited), did crash when I tapped the boost button. I saw a note several weeks ago that a rewrite of the Sharkey Mastodon API is in the works, so I don't know if it's worth spending much time on right now.

Edit: I just realized I'm running the develop branch and not the much newer appstore/testflight branch, so maybe this is out of date.

*** Assertion failure in -[_UIDiffableDataSourceUpdate initWithIdentifiers:sectionIdentifiers:action:desinationIdentifier:relativePosition:destinationIsSection:], _UIDiffableDataSourceHelpers.m:504
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Fatal: supplied item identifiers are not unique. Duplicate identifiers: {(
    Feditext.ReactionItem.reaction(reaction: Mastodon.Reaction(name: "❤", count: 1, me: true, url: nil, staticUrl: nil))
)}'

**Comment by VyrCossont** [comment] 2024-01-30 06:18
`develop` is long overdue for a merge, yes. And if Sharkey is high churn right now, I'll definitely wait for it to calm down.

**Comment by technicat** [comment] 2024-01-30 06:26
here's the note on a Mastodon API rewrite, from a couple of months ago but I haven't heard anything since

https://git.joinsharkey.org/Sharkey/Sharkey/issues/189

**Comment by VyrCossont** [comment] 2024-02-04 21:17
Here's a more detailed stack trace:

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Fatal: supplied item identifiers are not unique. Duplicate identifiers: {(
    Feditext.ReactionItem.reaction(reaction: Mastodon.Reaction(name: "❤", count: 3, me: false, url: nil, staticUrl: nil))
)}'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff80049928d __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff800063894 objc_exception_throw + 48
	2   Foundation                          0x00007ff800daec80 _userInfoForFileAndLine + 0
	3   UIKitCore                           0x00007ff806184504 -[_UIDiffableDataSourceUpdate initWithIdentifiers:sectionIdentifiers:action:desinationIdentifier:relativePosition:destinationIsSection:] + 804
	4   UIKitCore                           0x00007ff8061848e9 -[_UIDiffableDataSourceUpdate initWithItemIdentifiers:appendingToDestinationSectionIdentifier:] + 84
	5   UIKitCore                           0x00007ff8053f0fc5 -[__UIDiffableDataSourceSnapshot appendItemsWithIdentifiers:intoSectionWithIdentifier:] + 158
	6   UIKitCore                           0x00007ff804c20901 __swift_destroy_boxed_opaque_existential_1Tm + 15521
	7   Feditext                            0x0000000105bd5e00 $s8Feditext19StatusReactionsViewC9viewModel0D6Models0bdF0CSgvW + 672
	8   Feditext                            0x0000000105bd5b45 $s8Feditext19StatusReactionsViewC9viewModel0D6Models0bdF0CSgvs + 117
	9   Feditext                            0x0000000105b5b544 $s8Feditext10StatusViewC05applyB13Configuration33_B7CE5BBA0DFF5F544F65586181761533LLyyF + 15636
	10  Feditext                            0x0000000105b5023f $s8Feditext10StatusViewC13configurationAcA0B20ContentConfigurationV_tcfc + 4799
	11  Feditext                            0x0000000105b4ef6a $s8Feditext10StatusViewC13configurationAcA0B20ContentConfigurationV_tcfC + 42
	12  Feditext                            0x0000000105970169 $s8Feditext26StatusContentConfigurationV04makeC4View5UIKit09UIContentF0_So6UIViewCXcyF + 73
	13  Feditext                            0x000000010597023d $s8Feditext26StatusContentConfigurationV5UIKit09UIContentD0AadEP04makeC4ViewAD0fH0_So6UIViewCXcyFTW + 13
	14  UIKitCore                           0x00007ff804bd950c __swift_project_boxed_opaque_existential_1 + 20972
	15  UIKitCore                           0x00007ff805db81df -[UITableViewCell _applyContentViewConfiguration:withState:usingSPI:] + 1125
	16  UIKitCore                           0x00007ff804bd3abc block_destroy_helper.37 + 1260
	17  Feditext                            0x0000000105a19cc3 $s8Feditext19StatusTableViewCellC19updateConfiguration5usingy5UIKit06UICellG5StateV_tF + 435
	18  Feditext                            0x0000000105a19ebf $s8Feditext19StatusTableViewCellC19updateConfiguration5usingy5UIKit06UICellG5StateV_tFTo + 111
	19  UIKitCore                           0x00007ff805dbd482 -[UITableViewCell _performConfigurationStateUpdate] + 237
	20  UIKitCore                           0x00007ff805db183a -[UITableViewCell systemLayoutSizeFittingSize:withHorizontalFittingPriority:verticalFittingPriority:] + 60
	21  UIKitCore                           0x00007ff805e5dcaf -[UITableView _heightForCell:atIndexPath:] + 434
	22  UIKitCore                           0x00007ff805e43258 __53-[UITableView _configureCellForDisplay:forIndexPath:]_block_invoke + 2589
	23  UIKitCore                           0x00007ff80622eac4 +[UIView(Animation) performWithoutAnimation:] + 84
	24  UIKitCore                           0x00007ff805e427ee -[UITableView _configureCellForDisplay:forIndexPath:] + 243
	25  UIKitCore                           0x00007ff805e55dc3 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 1870
	26  UIKitCore                           0x00007ff805e1a957 -[UITableView _updateVisibleCellsForRanges:createIfNecessary:] + 788
	27  UIKitCore                           0x00007ff805e1b260 -[UITableView _updateVisibleCellsNow:] + 1800
	28  UIKitCore                           0x00007ff805e3d26e -[UITableView layoutSubviews] + 205
	29  UIKitCore                           0x00007ff80623cd07 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2141
	30  QuartzCore                          0x00007ff80aefec71 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 527
	31  UIKitCore                           0x00007ff8062272e8 -[UIView(Hierarchy) layoutBelowIfNeeded] + 1450
	32  UIKitCore                           0x00007ff805e2d5b0 -[UITableView reloadData] + 1719
	33  UIKit                               0x00007ff845144126 -[UITableViewAccessibility reloadData] + 44
	34  UIKitCore                           0x00007ff805e643c3 -[UITableView _performInternalBatchUpdates:] + 49
	35  UIKitCore                           0x00007ff805e64206 -[UITableView _performDiffableUpdate:] + 82
	36  UIKitCore                           0x00007ff804f4a241 -[_UIDiffableDataSourceViewUpdater _reloadData] + 333
	37  UIKitCore                           0x00007ff804f3ecba __56-[__UIDiffableDataSource reloadFromSnapshot:completion:]_block_invoke + 230
	38  libdispatch.dylib                   0x00000001092789f7 _dispatch_client_callout + 8
	39  libdispatch.dylib                   0x00000001092899a1 _dispatch_async_and_wait_invoke + 175
	40  libdispatch.dylib                   0x00000001092789f7 _dispatch_client_callout + 8
	41  libdispatch.dylib                   0x0000000109288856 _dispatch_main_queue_drain + 1362
	42  libdispatch.dylib                   0x00000001092882f6 _dispatch_main_queue_callback_4CF + 31
	43  CoreFoundation                      0x00007ff8003f5850 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	44  CoreFoundation                      0x00007ff8003f018b __CFRunLoopRun + 2463
	45  CoreFoundation                      0x00007ff8003ef409 CFRunLoopRunSpecific + 557
	46  GraphicsServices                    0x00007ff80fcdd187 GSEventRunModal + 137
	47  UIKitCore                           0x00007ff805b703a2 -[UIApplication _run] + 972
	48  UIKitCore                           0x00007ff805b74e10 UIApplicationMain + 123
	49  SwiftUI                             0x00007ff84a61077e __swift_memcpy18_8 + 2510
	50  SwiftUI                             0x00007ff84a610637 __swift_memcpy18_8 + 2183
	51  SwiftUI                             0x00007ff84a2bcaa5 objectdestroy.8Tm + 8912
	52  Feditext                            0x0000000105ba6d43 $s8Feditext11MetatextAppV5$mainyyFZ + 35
	53  Feditext                            0x0000000105ba6fb9 main + 9
	54  dyld                                0x00000001086023ee start_sim + 10
	55  ???                                 0x0000000117ad1386 0x0 + 4692185990
)
libc++abi: terminating due to uncaught exception of type NSException
```

**Comment by VyrCossont** [comment] 2024-02-04 21:34
Found it. This is caused by Sharkey sending both `Status.reactions` and `Status.emoji_reactions`, which no other server does, and by Feditext's persistence layer merging them when it should be using one or the other (like the UI layer). Fortunately, it's a two-line change to fix the persistence layer and add a low-impact workaround for existing persisted data that should get Sharkey users back in.

**Comment by VyrCossont** [comment] 2024-02-04 21:37
Should be fixed in build 86 by 3108689a395159432a994c74361c3ae9db59be54.

**Comment by NyaomiDEV** [comment] 2024-02-04 21:57
This particular crash is fixed.

Regarding reactions, local custom ones are not shown correctly and it's only possible to view emoji (Unicode) reactions and remote custom reactions. Everything else is an unintelligible small text.

Other issues are still present.

For example, notifications are not polled at all. Refreshing the list gives this out:

```json
{
  "alertLocation" : {
    "file" : "ViewModels/CollectionItemsViewModel.swift",
    "function" : "request(maxId:minId:search:)",
    "line" : 370
  },
  "app" : {
    "build" : "86",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "error" : {
    "error" : {
      "typeMismatch" : {
        "context" : {
          "codingPath" : [
            "_JSONKey(stringValue: \"Index 0\", intValue: 0)",
            "CodingKeys(stringValue: \"status\", intValue: nil)",
            "CodingKeys(stringValue: \"quote\", intValue: nil)",
            "CodingKeys(stringValue: \"quote\", intValue: nil)"
          ],
          "debugDescription" : "Expected to decode Dictionary<String, Any> but found bool instead."
        },
        "type" : "Swift.Dictionary<Swift.String, Any>"
      }
    },
    "method" : "GET",
    "requestLocation" : {
      "file" : "ServiceLayer/NotificationsService.swift",
      "function" : "request(maxId:minId:search:)",
      "line" : 69
    },
    "url" : "https://eepy.moe/api/v1/notifications"
  },
  "message" : "GET https://eepy.moe/api/v1/notifications\n\ntypeMismatch(type: \"Swift.Dictionary<Swift.String, Any>\", context: HTTP.AnnotatedDecodingError.EncodableContext(codingPath: [\"_JSONKey(stringValue: \\\"Index 0\\\", intValue: 0)\", \"CodingKeys(stringValue: \\\"status\\\", intValue: nil)\", \"CodingKeys(stringValue: \\\"quote\\\", intValue: nil)\", \"CodingKeys(stringValue: \\\"quote\\\", intValue: nil)\"], debugDescription: \"Expected to decode Dictionary<String, Any> but found bool instead.\", underlyingError: nil))",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "17.2.1"
  },
  "title" : "AnnotatedDecodingError",
  "type" : "AnnotatedDecodingError"
}
```

**Comment by VyrCossont** [comment] 2024-02-04 22:51
@NyaomiDEV Please open additional issues for different bugs. The emoji one especially, since that needs screenshots and some repro details.

Notifications are bug #360 and definitely Sharkey's fault. I've opened an upstream bug for that one already.

**Closed as completed by VyrCossont** 2024-02-04 22:51 UTC
Labels: bug, Misskey fork
