### ISSUE TITLE
“Followed by %@ and %@“ in “Favourited by” list

### ISSUE THREAD

**Issue by AngryAnt** [feditext/feditext#165] opened 2023-08-04 09:59 UTC
**Describe the bug**
In the “Favourited by” view of a given post, entries with following-overlap have incomplete string interpolation. The “Followed by” string listed under the registered URL listing of a user was in the observed case exactly “Followed by %@ and %@“ rather than having user handles or names swapped in.

**To Reproduce**
1. Go to a post which has been favourited by an account with follower overlap.2. 
2. Look at the accounts list in the “Favourited by” view by tapping the favourites (I did so via the notifications view).
3. Observe the malformed string on the appropriate account in the list.

**Expected behavior**
The user names/handles are properly substituted into the string.

**(please complete the following information):**
 - Device: iPhone 7.
 - OS: iOS 15.7.7.
 - App Version 1.7.2 (69).

**Comment by VyrCossont** [comment] 2023-08-04 19:44
Thanks! Another user reported this previously, also on iOS 15, although I don't think the report made it to this issue tracker. Since I've been unable to reproduce this on iOS 16, that narrows the scope down to a custom interpolator for attributed strings that uses the old regex API on iOS 15, so this shouldn't be too bad to fix.

**Comment by VyrCossont** [comment] 2024-02-03 04:56
Will be fixed by commit 503ecb2cda892b52ccb79c3573051992aa024ea5 in build 85.

**Closed as completed** 2024-02-04 21:53 UTC
Labels: bug
