### ISSUE TITLE
Unable to load image error while viewing the image

### ISSUE THREAD

**Issue by joan7770** [feditext/feditext#241] opened 2023-08-29 08:43 UTC
**Describe the bug**
When I open an image from posts from a certain user the image is loaded but an error shows up saying it failed to load the image. I think this may be instance app dependent. Images from fgc.network were causing the error to pop up.

**To Reproduce**
1. Tap a loaded image to expand it
2. Error appears

**Expected behavior**
View the image without an error showing

**Screenshots**
![image](https://github.com/feditext/feditext/assets/19157445/e6b72c2a-7cf9-44e3-bdb5-fdab8b52f9ef)

**(please complete the following information):**
 - Device: iPhone SE 2020 version 
 - OS: iOS 16.6 (20G75)
 - App Version: TestFlight build 1.7.2 (74)

**Additional context**

Error Json from error message:
```Json
{
  "alertLocation" : {
    "file" : "Feditext/ImageViewController.swift",
    "function" : "viewDidLoad()",
    "line" : 150
  },
  "app" : {
    "build" : "74",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "message" : "Unable to load image",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "16.6"
  },
  "title" : "ImageError",
  "type" : "ImageError"
}
```

**Comment by VyrCossont** [comment] 2023-08-29 17:41
Dupe of #238.

**Closed as completed by VyrCossont** 2023-08-29 17:41 UTC
Labels: duplicate
