### ISSUE TITLE
formatting wrong with blockquote

### ISSUE THREAD

**Issue by adamse** [feditext/feditext#230] opened 2023-08-23 14:14 UTC
**Describe the bug**
Blockquote styling is partially overlapping with following text.

**To Reproduce**
1. View https://benjojo.co.uk/u/benjojo/h/4m1f3YL65Wq415L747 in the app

**Expected behavior**

Following text is not inside quote block.

**(please complete the following information):**
 - Device: iphone 13
 - OS: 16.6
 - App Version: 1.7.2 (72)

![IMG_2740](https://github.com/feditext/feditext/assets/75746/7ab9d0de-fb96-4b7d-aa49-1c7f9410c36e)

**Comment by VyrCossont** [comment] 2023-08-23 19:27
Thanks for the report. This is a duplicate of a known issue, #164.

**Closed as completed by VyrCossont** 2023-08-23 19:27 UTC
Labels: duplicate

**Comment by VyrCossont** [comment] 2023-08-23 19:29
The post came from a Honk instance. @adamse what kind of instance are you using yourself?

**Comment by adamse** [comment] 2023-08-23 20:04
normal mastodon instance.
