### ISSUE TITLE
WriteFreely posts don’t open link to blog post

### ISSUE THREAD

**Issue by rrgeorge** [feditext/feditext#203] opened 2023-08-14 18:23 UTC
**Describe the bug**
WriteFreely posts show up as just the title and a link to the blog post (in Mastodon, at least), and clicking the link just reopens that “summary post” in Feditext

**To Reproduce**
1. Follow a WriteFreely blog
2. When a new post is published, see the post in Feditext is the title with a link 
3. Click the link
4. See the same post reopen

**Expected behavior**
A (in-app?) browser window should open the full blogpost. 

**Screenshots**
https://github.com/feditext/feditext/assets/8526392/fc83fdce-61e3-4877-bd1e-55894454a0a4

**(please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 16.6
 - App Version 1.7.2 (70)

**Additional context**
Server is running Mastodon 4.1.6

**Comment by VyrCossont** [comment] 2023-08-14 19:00
Dupe of #182. For now, you can work around it by using the share button to open it in your default browser.

**Closed as completed by VyrCossont** 2023-08-14 19:00 UTC
Labels: duplicate
