### ISSUE TITLE
Add Support for SNAC

### ISSUE THREAD

**Issue by allluke** [feditext/feditext#372] opened 2024-02-14 07:38 UTC
**Is your feature request related to a problem? Please describe.**
I can't login with Snac

**Describe the solution you'd like**
I want to use feditext with my snac server

**Describe alternatives you've considered**
Mona app works

**Additional context**
https://codeberg.org/grunfink/snac2

**Comment by VyrCossont** [comment] 2024-02-14 18:43
Dupe of #348.

**Closed as not planned by VyrCossont** 2024-02-14 18:43 UTC
Labels: duplicate, enhancement
