### ISSUE TITLE
Scrolling Stutter

### ISSUE THREAD

**Issue by melgu** [feditext/feditext#256] opened 2023-09-22 00:04 UTC
**Describe the bug**
When I use the app and scroll in the different views (timeline, notifications etc.) there are a lot of stutters.

**To Reproduce**
1. Open the app
2. Make sure, you're logged in
3. Scroll around

**Expected behavior**
The scrolling is fluid without any hiccups or stutters.

**Screenshots**
https://github.com/feditext/feditext/assets/9601403/a14cb43a-c8d2-40bb-a893-83d4becb73c4

**(please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS 17.0.1
 - App Version: 1.7.2 (75)

**Additional context**
Doesn't happen in Metatext.

**Comment by bhalperin28** [comment] 2023-09-22 00:47
This is a duplicate of https://github.com/feditext/feditext/issues/253.

**Closed as not planned** 2023-09-22 00:49 UTC
