### ISSUE TITLE
The loop when I click the hyperlink at Snopes mirror

### ISSUE THREAD

**Issue by SoraX6** [feditext/feditext#262] opened 2023-09-30 20:32 UTC
The Bug

When I try to access the Snopes website via the hyperlink provided by the website mirror it endlessly loops. 

1. Click on Feditext app
2. Click on explore icon and type (or copy and paste): @snopescomputers@social.trom.tf and enter
3. Click on any hyperlink provided by the mirror
4. See error (the loop)

 - Device:  iPhone XR
 - OS: iOS 17.0.2
 - App Version 1.7.1 (76)

**Comment by bdube** [comment] 2023-09-30 20:45
Hi, thanks for the report. When I click the website link in the bio, I don't see a repro. Does that link work for you? Is the issue with links in posts?

**Comment by SoraX6** [comment] 2023-09-30 20:49
> Hi, thanks for the report. When I click the website link in the bio, I don't see a repro. Does that link work for you? Is the issue with links in posts?

Should I provide the video? 

The issue is the with all the links in the posts. Almost all of them behave in similar manner.

**Comment by SoraX6** [comment] 2023-09-30 21:06
I have updated it with more details, I hope it is more clear now.

**Comment by bdube** [comment] 2023-09-30 21:25
Thanks. It appears to be Friendica 2023.05. In Feditext, I followed the link in the bio of @snopescomputers@social.trom.tf and that works for me. Does it work for you?

When a link in a post loops for you, can you tell if it's trying to follow a link to the article on www.snopes.com or to the post on social.trom.tf?

**Comment by SoraX6** [comment] 2023-09-30 21:34
Yes, the link in bio worked for me as you mentioned. 

I try to click on the hyperlink, it leads to the post from the social.trom.tf. I do it in order to reach the article. It seems to follow the post on social.trom.tf.

**Comment by mindshoot** [comment] 2023-10-03 06:59
Is this the same kind of loop as I get when trying to open the article in this post?

https://blog.josh.tel/2023/09/29/stop-defining-people-by-what-theyre-not-on-non-code-contributors/

If I open a post containing that link, I also end up in a loop, and the only way to actually read the article is to copy the link manually into a browser. If it’s a different issue, I can fine separately. 

Edit: checked and looks like the same issue to me.

**Comment by mediaformat** [comment] 2023-10-07 18:21
I think this is an issue with WordPress based posts, like this one for example: https://wedistribute.org/2023/09/connect-wordpress-to-the-fediverse/

**Comment by bdube** [comment] 2023-10-07 18:35
@mediaformat The first time I followed that link in the browser, I got a json response. Then I went to the website and followed the link from there and got the expected html. The url is the same. Then I came back and followed the link from this issue again and got html.

I don't know what this means. Sorry if it's unrelated.

**Comment by mediaformat** [comment] 2023-10-21 13:47
> I got a json response.
> I don't know what this means. Sorry if it's unrelated.

Yes that is an unrelated server config issue for that instance.

**Comment by mediaformat** [comment] 2023-10-21 13:52
This appears to be a duplicate of https://github.com/feditext/feditext/issues/182

**Closed as not planned** 2024-02-03 05:05 UTC
Labels: duplicate, TODO: confirm repro
