### ISSUE TITLE
CW text is not distinct from post text, "Show more" button is excessively present

### ISSUE THREAD

**Issue by ShadowJonathan** [feditext/feditext#351] opened 2024-01-30 13:15 UTC
This is a suggestion borne from an initial impression of metatext, but to decrease on visual clutter and ambiguity, could the "show more" and CW text be merged into one button? (CW text inside of a big green/colored button)

----

Currently, the CW text only has barely more font weight than other text, making it visually almost indistinguishable.

The "Show more" button also then melds together with the "show thread" button, which then results in a very awkward visual hierarchy to look through.

**Comment by VyrCossont** [comment] 2024-02-02 18:43
Dupe of #346.

**Closed as completed by VyrCossont** 2024-02-02 18:43 UTC
Labels: duplicate
