### ISSUE TITLE
Gap in timeline feed after clicking on “Load more”

### ISSUE THREAD

**Issue by theppn** [feditext/feditext#295] opened 2023-11-06 23:58 UTC
**Describe the bug**
I recently changed phones and after reinstalling the beta on my new phone, I wanted to load the missing posts between now and when I last used the app 9 days ago. It did not work, failed silently and just showed me a feed with a noticeable time gap as if nothing was posted since then. 

**To Reproduce**
1. On a new phone, do not launch the app for a few days, in my case it was 9 days. 
2. Click on “load more”
3. See the gap in feed and compare the missing posts on another device. 

**Expected behavior**
I should see the posts between now and 9 days ago. At the very least I should see an error or a visual cue telling me that some posts could not be loaded or are missing. 

**Screenshots**
Picture with the bug:
https://imgur.io/uBJgjoc?r
Picture of what the first next post should be:
https://imgur.io/gkm9JDW?r

**(please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 17.0.3
 - App Version: 1.7.2 (77)

**Additional context**
Not sure if it is relevant but the new phone’s data was obviously transferred from the old one.

**Comment by VyrCossont** [comment] 2023-11-07 00:32
@theppn Please downgrade to build 76 through TestFlight. This is a known bug in build 77.

**Comment by VyrCossont** [comment] 2023-11-07 22:38
Duplicate of #290. Fix going out today.

**Closed as completed by VyrCossont** 2023-11-07 22:38 UTC
Labels: bug, duplicate
