### ISSUE TITLE
Json error

### ISSUE THREAD

**Issue by searchtools-avi** [feditext/feditext#280] opened 2023-10-17 23:56 UTC
This came up after arriving home, probably switching from cellular to wifi. Earlier, I got shorter errors as I was out for a hike and frequently losing the cell connection. Hope it helps. 

```json
{
  "alertLocation" : {
    "file" : "ViewModels/CollectionItemsViewModel.swift",
    "function" : "init(collectionService:identityContext:)",
    "line" : 35
  },
  "app" : {
    "build" : "76",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "message" : "SQLite error 9: interrupted - while executing `SELECT \"statusRecord1\".*, \"timelineStatusJoin\".\"timelineId\" AS \"grdb_timelineId\", \"accountRecord1\".*, \"accountRecord2\".*, \"relationship1\".*, \"statusRecord2\".*, \"accountRecord4\".*, \"accountRecord5\".*, \"relationship2\".*, \"statusShowContentToggle1\".*, \"statusShowAttachmentsToggle1\".*, \"statusRecord3\".*, \"accountRecord7\".*, \"accountRecord8\".*, \"relationship3\".*, \"statusShowContentToggle2\".*, \"statusShowAttachmentsToggle2\".*, \"statusShowContentToggle3\".*, \"statusShowAttachmentsToggle3\".* FROM \"statusRecord\" \"statusRecord1\" JOIN \"accountRecord\" \"accountRecord1\" ON \"accountRecord1\".\"id\" = \"statusRecord1\".\"accountId\" LEFT JOIN \"accountRecord\" \"accountRecord2\" ON \"accountRecord2\".\"id\" = \"accountRecord1\".\"movedId\" LEFT JOIN \"accountRecord\" \"accountRecord3\" ON \"accountRecord3\".\"id\" = \"statusRecord1\".\"accountId\" LEFT JOIN \"relationship\" \"relationship1\" ON \"relationship1\".\"id\" = \"accountRecord3\".\"id\" LEFT JOIN \"statusRecord\" \"statusRecord2\" ON \"statusRecord2\".\"id\" = \"statusRecord1\".\"quoteId\" LEFT JOIN \"accountRecord\" \"accountRecord4\" ON \"accountRecord4\".\"id\" = \"statusRecord2\".\"accountId\" LEFT JOIN \"accountRecord\" \"accountRecord5\" ON \"accountRecord5\".\"id\" = \"accountRecord4\".\"movedId\" LEFT JOIN \"accountRecord\" \"accountRecord6\" ON \"accountRecord6\".\"id\" = \"statusRecord2\".\"accountId\" LEFT JOIN \"relationship\" \"relationship2\" ON \"relationship2\".\"id\" = \"accountRecord6\".\"id\" LEFT JOIN \"statusShowContentToggle\" \"statusShowContentToggle1\" ON \"statusShowContentToggle1\".\"statusId\" = \"statusRecord2\".\"id\" LEFT JOIN \"statusShowAttachmentsToggle\" \"statusShowAttachmentsToggle1\" ON \"statusShowAttachmentsToggle1\".\"statusId\" = \"statusRecord2\".\"id\" LEFT JOIN \"statusRecord\" \"statusRecord3\" ON \"statusRecord3\".\"id\" = \"statusRecord1\".\"reblogId\" LEFT JOIN \"accountRecord\" \"accountRecord7\" ON \"accountRecord7\".\"id\" = \"statusRecord3\".\"accountId\" LEFT JOIN \"accountRecord\" \"accountRecord8\" ON \"accountRecord8\".\"id\" = \"accountRecord7\".\"movedId\" LEFT JOIN \"accountRecord\" \"accountRecord9\" ON \"accountRecord9\".\"id\" = \"statusRecord3\".\"accountId\" LEFT JOIN \"relationship\" \"relationship3\" ON \"relationship3\".\"id\" = \"accountRecord9\".\"id\" LEFT JOIN \"statusShowContentToggle\" \"statusShowContentToggle2\" ON \"statusShowContentToggle2\".\"statusId\" = \"statusRecord3\".\"id\" LEFT JOIN \"statusShowAttachmentsToggle\" \"statusShowAttachmentsToggle2\" ON \"statusShowAttachmentsToggle2\".\"statusId\" = \"statusRecord3\".\"id\" LEFT JOIN \"statusShowContentToggle\" \"statusShowContentToggle3\" ON \"statusShowContentToggle3\".\"statusId\" = \"statusRecord1\".\"id\" LEFT JOIN \"statusShowAttachmentsToggle\" \"statusShowAttachmentsToggle3\" ON \"statusShowAttachmentsToggle3\".\"statusId\" = \"statusRecord1\".\"id\" JOIN \"timelineStatusJoin\" ON (\"timelineStatusJoin\".\"statusId\" = \"statusRecord1\".\"id\") AND (\"timelineStatusJoin\".\"timelineId\" = ?) ORDER BY \"statusRecord1\".\"id\" DESC`",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "16.7.1"
  },
  "title" : "DatabaseError",
  "type" : "DatabaseError"
}
```

**Comment by VyrCossont** [comment] 2023-11-06 21:48
Thanks for the report.

**Comment by VyrCossont** [comment] 2024-03-20 16:35
Dupe of #277.

**Closed as not planned by VyrCossont** 2024-03-20 16:35 UTC
Labels: duplicate
