### ISSUE TITLE
Can’t list timeline on a Sharkey account

### ISSUE THREAD

**Issue by QurQuma** [feditext/feditext#395] opened 2024-03-30 07:24 UTC
Listing timeline returns error with this json:

```json
{
  "alertLocation" : {
    "file" : "ViewModels/CollectionItemsViewModel.swift",
    "function" : "request(maxId:minId:)",
    "line" : 371
  },
  "app" : {
    "build" : "100",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "error" : {
    "error" : {
      "typeMismatch" : {
        "context" : {
          "codingPath" : [
            "_JSONKey(stringValue: \"Index 0\", intValue: 0)",
            "CodingKeys(stringValue: \"quote\", intValue: nil)"
          ],
          "debugDescription" : "Expected to decode Dictionary<String, Any> but found bool instead."
        },
        "type" : "Swift.Dictionary<Swift.String, Any>"
      }
    },
    "method" : "GET",
    "requestLocation" : {
      "file" : "ServiceLayer/TimelineService.swift",
      "function" : "request(maxId:minId:)",
      "line" : 93
    },
    "url" : "https://tacticalpedia.me/api/v1/timelines/home"
  },
  "message" : "GET https://tacticalpedia.me/api/v1/timelines/home\n\ntypeMismatch(type: \"Swift.Dictionary<Swift.String, Any>\", context: HTTP.AnnotatedDecodingError.EncodableContext(codingPath: [\"_JSONKey(stringValue: \\\"Index 0\\\", intValue: 0)\", \"CodingKeys(stringValue: \\\"quote\\\", intValue: nil)\"], debugDescription: \"Expected to decode Dictionary<String, Any> but found bool instead.\", underlyingError: nil))",
  "system" : {
    "idiom" : "pad",
    "model" : "iPad",
    "name" : "iPadOS",
    "version" : "17.3.1"
  },
  "title" : "AnnotatedDecodingError",
  "type" : "AnnotatedDecodingError"
}
```

**(please complete the following information):**
 - Device: iPad
 - OS: iPadOS
 - App Version 1.7.2

**Comment by VyrCossont** [comment] 2024-04-01 17:32
Duplicate of #360.

**Closed as not planned** 2024-04-01 17:33 UTC
Labels: duplicate, Misskey fork, server bug
